name: Code checks
on:
  [pull_request]
jobs:
  build_check:
    runs-on: ubuntu-latest
    container:
      image: node:16.13.0-alpine
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Build check
        run: npm run build

  codestyle:
    needs: build_check
    runs-on: ubuntu-latest
    container:
      image: node:16.13.0-alpine
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Lint source code with Eslint
        run: npm run linter

  types:
    needs: build_check
    runs-on: ubuntu-latest
    container:
      image: node:16.13.0-alpine
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Check types
        run: npm run check:ts

  tests:
    needs: build_check
    runs-on: ubuntu-latest
    container:
      image: node:16.13.0-alpine
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Run tests
        run: npm run test

  deploy:
    name: Deploy project to Yandex Cloud
    needs: ['tests', 'types', 'codestyle']
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/production
          chmod 600 ~/.ssh/production
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/production
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.SSH_SECRET_KEY }}
          SSH_USER: ${{ secrets.SSH_USER_NAME }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Stop the docker
        run: ssh production 'cd runner-game'
